name: Build Infra
on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'

jobs:
  infrabuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3

      - name: Terraform init
        id: init
        working-directory: ./infra
        run: terraform init

      - name: Terraform plan
        id: plan
        working-directory: ./infra
        run: terraform plan -var=${{ secrets.AWS_CLUSTER_ROLE }}
    